"""Development is over

Revision ID: c61f0005733b
Revises:
Create Date: 2022-09-18 17:46:55.025518

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c61f0005733b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("Name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("Name"),
    )
    op.create_index(op.f("ix_users_Name"), "users", ["Name"], unique=True)
    op.create_table(
        "parameters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("Name", sa.String(length=50), nullable=True),
        sa.Column("Type", sa.String(length=10), nullable=True),
        sa.Column("Value", sa.String(), nullable=True),
        sa.Column("Username", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["Username"],
            ["users.Name"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_parameters_id"), "parameters", ["id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_parameters_id"), table_name="parameters")
    op.drop_table("parameters")
    op.drop_index(op.f("ix_users_Name"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
