"""Init

Revision ID: 72750a40b97c
Revises:
Create Date: 2022-09-10 21:28:50.782002

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "72750a40b97c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parameters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=True),
        sa.Column("type", sa.String(length=10), nullable=True),
        sa.Column("value", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_parameters_id"), "parameters", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_parameters_id"), table_name="parameters")
    op.drop_table("parameters")
    # ### end Alembic commands ###
