name: Test after deploying

on:
  workflow_dispatch:

  push:
    branches: [master]

  pull_request:
    branches: [master]

jobs:
  test:
    name: Test run argstore:latest from ghcr on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Run argstore:latest
        run: |
          mkdir db_folder
          docker run -d -p 8000:8000 -e SQLALCHEMY_DATABASE_URL=sqlite:////app/db/argstore.db -e INIT_NOT_EXISTED_DB=True -v `readlink -f db_folder`:/app/db ghcr.io/fleshofcat/argstore:latest

      - name: Wait the argstore container to start
        run: wget -qO- https://raw.githubusercontent.com/eficode/wait-for/$WAIT_FOR_VERSION/wait-for | sh -s -- http://localhost:8000/docs -- echo "argstore is up"
        env:
          WAIT_FOR_VERSION: 4df3f9262d84cab0039c07bf861045fbb3c20ab7 # v2.2.3

      - uses: actions/checkout@v2
      - run: curl localhost:8000/docs

      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3

      # - run: |
      #     status_code=`curl --write-out %{http_code} --silent --output /dev/null localhost:8000/`
      #     if [[ "$status_code" != 307 ]] ; then
      #       exit -1
      #     else
      #       exit 0
      #     fi
